CLASS zcl_bp_i_fixedasset DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zi_fixedasset.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_bp_i_fixedasset IMPLEMENTATION.
ENDCLASS.